### ISSUE TITLE
Is there a plan to release the version with 0.8.2 support?

### ISSUE THREAD

**Issue by gregsilin** [gilt/sbt-dependency-graph-sugar#15]
Hi,

I see this commit that enables support for version 0.8.2 of the underlying dependency graph plugin: https://github.com/gilt/sbt-dependency-graph-sugar/commit/ad31204eda9c81860b3795e2b11ae8fd8b4c26cb

Are there plans to publish & release that version of the `sbt-dependency-graph-sugar` plugin?

**Comment by gheine** [comment]
0.8.2 was released in July. See http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.gilt%22%20AND%20a%3A%22sbt-dependency-graph-sugar%22

**Comment by gheine** [comment]
It was just missing a tag. :)

**Comment by gregsilin** [comment]
@gheine my apologies, thanks for the pointer.
