### ISSUE TITLE
Hiding basic SBT imports

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [gilt/sbt-dependency-graph-sugar#6]
I've experienced [this problem](http://stackoverflow.com/questions/28428014/imports-and-ill-behaved-sbt-plugins/28428045#28428045) when working with `inputKeys`.

I would like to avoid namespace clashes with basic SBT classes.

**Comment by stjohnb** [comment]
I've tried to reproduce this issue in this commit 2269f4ef2e9eff9c3193a1b0111f30b20321c5d2 but my test case does not produce the error you describe.

Could you update that test case to make it fail or point me to a project which has the issue?

**Comment by DavidPerezIngeniero** [comment]
Sorry, I don't have time now to investigate this.

**Comment by gheine** [comment]
Can't reproduce
