### ISSUE TITLE
Add support for sbt 0.13.8

### ISSUE THREAD

**Issue by vhiairrassary** [gilt/sbt-dependency-graph-sugar#7]
Hello,

Can you release a new version of sbt-dependency-graph-sugar as sbt-dependency-graph have just bump to 0.7.5 to support sbt 0.13.8 (https://github.com/jrudolph/sbt-dependency-graph/commit/2e3a8fa168b57004ef867481a5974c1f734484f1).

Thanks in advance

**Comment by xuwei-k** [comment]
+1

**Comment by yardena** [comment]
+1

**Comment by stjohnb** [comment]
0.7.5 is now available @ https://oss.sonatype.org/content/repositories/releases/com/gilt/sbt-dependency-graph-sugar_2.10_0.13/0.7.5/
