### ISSUE TITLE
After upgrading to SBT 0.13.8 it doesn't work

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [gilt/sbt-dependency-graph-sugar#9]
After upgrading to SBT 0.13.8 from 0.13.7, I get this error:

```
> dependencyGraph
[trace] Stack trace suppressed: run last compile:ivyReport for the full output.
[error] (compile:ivyReport) java.lang.IllegalStateException: sbt-dependency-graph plugin currently only supports InlineConfiguration of ivy settings (the default in sbt)
```

**Comment by Seanstoppable** [comment]
Did you upgrade the plugin? Latest release should have had a fix for that, with the inclusion of [this change set](https://github.com/gilt/sbt-dependency-graph-sugar/commit/ac7964c47e1e4197e4667e1a7f86b38f2ac5acc0)

**Comment by DavidPerezIngeniero** [comment]
Sorry, I forgot to update.

**Comment by Seanstoppable** [comment]
No problem. Ran into the same problem myself initially.
